export const YEAR = '2021'
export const TITLE = 'A-Z - The Tech Notebook'
export const DESCRIPTION = 'Glossary of Terms, Notes and Links.'
export const AUTHOR = 'Nina Armangué Braun'
export const URL = 'https://nina.vercel.app'
export const CMS_NAME = 'Markdown'
export const HOME_OG_IMAGE_URL = 'https://nina.vercel.app/images/banner.jpg'
